vscode:
  extensions:
    - cyrilletuzi.angular-schematics@2.2.0:fcvnmTtm/saNrBf7ZZBPQw==
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.3:MioHhlbqHKgivweg8MqHrA==
    - vscode-icons-team.vscode-icons@9.6.0:pdLRjQynPhO1i+KaGm8EjA==
    - Angular.ng-template@0.900.0:+zD6sFzwleIgNNsDrLRqnw==
    - apollographql.vscode-apollo@1.12.1:0Ub6H46dWhAlGY8zWMaZBw==